import os

NAMESPACE_FOR_BUCKET_RESOURCE = os.environ["NAMESPACE_FOR_BUCKET_RESOURCE"]
MINIO_ROOT_PASSWORD = os.environ["MINIO_ROOT_PASSWORD"]
MINIO_ROOT_USER = os.environ["MINIO_ROOT_USER"]
MINIO_SERVER_ENDPOINT = os.environ["MINIO_SERVER_ENDPOINT"]
